2019-09-02 16:10:19,794 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_sheet ][__file__:27]- 操作EXCEL表类获取sheet页内容异常，异常原因：[Errno 2] No such file or directory: '../data_file/case_data_ysc.xlsx'
2019-09-02 16:10:19,794 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_sheet_rows ][__file__:35]- 操作EXCEL表类获取行数异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-02 16:10:19,794 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_row_col_list ][__file__:84]- 操作EXCEL表类获取值对应的行号出现异常，异常原因：'NoneType' object cannot be interpreted as an integer
2019-09-02 16:10:19,794 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：'NoneType' object is not subscriptable
2019-09-02 16:10:19,794 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_sheet ][__file__:27]- 操作EXCEL表类获取sheet页内容异常，异常原因：[Errno 2] No such file or directory: '../data_file/case_data_ysc.xlsx'
2019-09-02 16:10:19,794 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_sheet_rows ][__file__:35]- 操作EXCEL表类获取行数异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-02 16:10:19,794 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_row_col_list ][__file__:84]- 操作EXCEL表类获取值对应的行号出现异常，异常原因：'NoneType' object cannot be interpreted as an integer
2019-09-02 16:10:19,795 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：'NoneType' object is not subscriptable
