2019-09-11 10:20:33,343 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_sheet ][__file__:37]- 操作EXCEL表类获取sheet页内容异常，异常原因：[Errno 2] No such file or directory: '../case_file/BQ_JC_QZ_CASE.xlsx'
2019-09-11 10:20:33,345 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [__init__ ][__file__:19]- 操作EXCEL表类初始化异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-11 10:20:33,345 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_sheet ][__file__:37]- 操作EXCEL表类获取sheet页内容异常，异常原因：[Errno 2] No such file or directory: '../case_file/BQ_JC_QZ_CASE.xlsx'
2019-09-11 10:20:33,346 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_row_col_list_param_name ][__file__:182]- 操作EXCEL表类获取值对应的行号出现异常，异常原因：'NoneType' object has no attribute 'row_values'
2019-09-11 10:20:33,346 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：'NoneType' object is not subscriptable
2019-09-11 10:20:33,347 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_sheet ][__file__:37]- 操作EXCEL表类获取sheet页内容异常，异常原因：[Errno 2] No such file or directory: '../case_file/BQ_JC_QZ_CASE.xlsx'
2019-09-11 10:20:33,347 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_row_col_list ][__file__:153]- 操作EXCEL表类获取值对应的行号出现异常，异常原因：'NoneType' object has no attribute 'row_values'
2019-09-11 10:20:33,348 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：'NoneType' object is not subscriptable
2019-09-11 10:20:33,348 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：'NoneType' object is not subscriptable
2019-09-11 10:20:33,349 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/common_param_dic.py] [get_param_name_value ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/common_param_dic.py:114]- 接口参数处理类处理参数名与参数值方法异常，异常原因：object of type 'NoneType' has no len()
2019-09-11 10:21:00,733 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_sheet ][__file__:37]- 操作EXCEL表类获取sheet页内容异常，异常原因：[Errno 2] No such file or directory: '../case_file/BQ_JC_QZ_CASE.xlsx'
2019-09-11 10:21:00,734 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [__init__ ][__file__:19]- 操作EXCEL表类初始化异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-11 10:21:00,735 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_sheet ][__file__:37]- 操作EXCEL表类获取sheet页内容异常，异常原因：[Errno 2] No such file or directory: '../case_file/BQ_JC_QZ_CASE.xlsx'
2019-09-11 10:21:00,735 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_row_col_list_param_name ][__file__:182]- 操作EXCEL表类获取值对应的行号出现异常，异常原因：'NoneType' object has no attribute 'row_values'
2019-09-11 10:21:00,736 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：'NoneType' object is not subscriptable
2019-09-11 10:21:00,736 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_sheet ][__file__:37]- 操作EXCEL表类获取sheet页内容异常，异常原因：[Errno 2] No such file or directory: '../case_file/BQ_JC_QZ_CASE.xlsx'
2019-09-11 10:21:00,737 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_row_col_list ][__file__:153]- 操作EXCEL表类获取值对应的行号出现异常，异常原因：'NoneType' object has no attribute 'row_values'
2019-09-11 10:21:00,737 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：'NoneType' object is not subscriptable
2019-09-11 10:21:00,738 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：'NoneType' object is not subscriptable
2019-09-11 10:21:00,738 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/common_param_dic.py] [get_param_name_value ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/common_param_dic.py:114]- 接口参数处理类处理参数名与参数值方法异常，异常原因：object of type 'NoneType' has no len()
2019-09-11 10:21:14,516 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_sheet ][__file__:37]- 操作EXCEL表类获取sheet页内容异常，异常原因：[Errno 2] No such file or directory: '../case_file/BQ_JC_QZ_CASE.xlsx'
2019-09-11 10:21:14,516 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [__init__ ][__file__:19]- 操作EXCEL表类初始化异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-11 10:21:14,517 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_sheet ][__file__:37]- 操作EXCEL表类获取sheet页内容异常，异常原因：[Errno 2] No such file or directory: '../case_file/BQ_JC_QZ_CASE.xlsx'
2019-09-11 10:21:14,517 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_row_col_list_param_name ][__file__:182]- 操作EXCEL表类获取值对应的行号出现异常，异常原因：'NoneType' object has no attribute 'row_values'
2019-09-11 10:21:14,517 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：'NoneType' object is not subscriptable
2019-09-11 10:21:14,517 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_sheet ][__file__:37]- 操作EXCEL表类获取sheet页内容异常，异常原因：[Errno 2] No such file or directory: '../case_file/BQ_JC_QZ_CASE.xlsx'
2019-09-11 10:21:14,517 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_row_col_list ][__file__:153]- 操作EXCEL表类获取值对应的行号出现异常，异常原因：'NoneType' object has no attribute 'row_values'
2019-09-11 10:21:14,517 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：'NoneType' object is not subscriptable
2019-09-11 10:21:14,517 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：'NoneType' object is not subscriptable
2019-09-11 10:21:17,473 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/common_param_dic.py] [get_param_name_value ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/common_param_dic.py:114]- 接口参数处理类处理参数名与参数值方法异常，异常原因：object of type 'NoneType' has no len()
2019-09-11 10:21:45,582 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 10:21:45,762 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 10:21:45,762 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 10:21:55,132 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 10:21:55,133 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 10:21:55,138 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 10:22:04,224 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/common_param_dic.py] [encry ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/common_param_dic.py:132]- 接口参数处理类将文件转为文件流方法异常，异常原因：[Errno 2] No such file or directory: '../hz_file/xzhx.jpg'
2019-09-11 11:18:56,265 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 11:18:56,439 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 11:18:56,440 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 11:19:01,700 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 11:19:01,701 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 11:19:01,706 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 11:19:04,356 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/common_param_dic.py] [encry ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/common_param_dic.py:132]- 接口参数处理类将文件转为文件流方法异常，异常原因：[Errno 2] No such file or directory: '../hz_file/xzhx.jpg'
2019-09-11 11:20:31,003 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 11:20:31,177 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 11:20:31,178 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 11:20:33,567 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 11:20:33,568 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 11:20:33,576 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 11:20:35,311 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/common_param_dic.py] [encry ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/common_param_dic.py:132]- 接口参数处理类将文件转为文件流方法异常，异常原因：[Errno 2] No such file or directory: '../hz_file/xzhx.jpg'
2019-09-11 11:22:58,637 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 11:22:58,811 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 11:22:58,811 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 11:23:00,013 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 11:23:00,013 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 11:23:00,014 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 11:23:01,290 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/common_param_dic.py] [encry ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/common_param_dic.py:132]- 接口参数处理类将文件转为文件流方法异常，异常原因：[Errno 2] No such file or directory: '../hz_file/xzhx.jpg'
2019-09-11 11:27:19,370 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 11:27:19,555 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 11:27:19,556 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 11:27:22,801 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 11:27:22,802 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 11:27:22,807 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 11:27:24,753 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/common_param_dic.py] [encry ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/common_param_dic.py:132]- 接口参数处理类将文件转为文件流方法异常，异常原因：[Errno 2] No such file or directory: '../hz_file/xzhx.jpg'
2019-09-11 11:28:17,748 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 11:28:20,969 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 11:28:21,542 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 11:28:23,278 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 11:28:23,279 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 11:28:45,552 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 11:28:52,126 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/common_param_dic.py] [encry ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/common_param_dic.py:132]- 接口参数处理类将文件转为文件流方法异常，异常原因：[Errno 2] No such file or directory: '../hz_file/xzhx.jpg'
2019-09-11 11:29:05,511 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 11:29:08,362 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 11:29:08,363 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 11:29:10,156 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 11:29:10,157 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 11:29:10,161 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 11:29:12,711 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/common_param_dic.py] [encry ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/common_param_dic.py:132]- 接口参数处理类将文件转为文件流方法异常，异常原因：[Errno 2] No such file or directory: '../hz_file/xzhx.jpg'
2019-09-11 12:57:15,962 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 12:57:20,128 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 12:57:21,784 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 12:57:24,139 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 12:57:24,140 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 12:57:27,275 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 12:57:29,653 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/common_param_dic.py] [encry ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/common_param_dic.py:132]- 接口参数处理类将文件转为文件流方法异常，异常原因：[Errno 2] No such file or directory: '../hz_file/xzhx.jpg'
2019-09-11 12:58:32,706 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 12:58:32,873 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 12:58:32,874 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 12:58:35,243 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 12:58:35,244 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 12:58:35,245 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 12:58:38,420 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/common_param_dic.py] [encry ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/common_param_dic.py:132]- 接口参数处理类将文件转为文件流方法异常，异常原因：[Errno 2] No such file or directory: '../hz_file/xzhx.jpg'
2019-09-11 12:59:13,567 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 12:59:13,734 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 12:59:13,735 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 12:59:18,664 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 12:59:18,664 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 12:59:18,666 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 12:59:20,763 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/common_param_dic.py] [encry ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/common_param_dic.py:132]- 接口参数处理类将文件转为文件流方法异常，异常原因：[Errno 2] No such file or directory: '../hz_file/xzhx.jpg'
2019-09-11 12:59:54,392 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 12:59:54,562 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 12:59:54,563 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 12:59:55,898 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 12:59:55,899 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 12:59:55,904 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 12:59:58,007 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/common_param_dic.py] [encry ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/common_param_dic.py:132]- 接口参数处理类将文件转为文件流方法异常，异常原因：[Errno 2] No such file or directory: '../hz_file/xzhx.jpg'
2019-09-11 13:00:26,219 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 13:00:26,395 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 13:00:26,395 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 13:00:27,641 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 13:00:27,643 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 13:00:27,647 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 13:00:29,618 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/common_param_dic.py] [encry ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/common_param_dic.py:132]- 接口参数处理类将文件转为文件流方法异常，异常原因：[Errno 2] No such file or directory: '../hz_file/xzhx.jpg'
2019-09-11 13:03:01,886 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 13:03:02,058 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 13:03:02,058 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 13:03:03,932 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 13:03:03,933 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 13:03:03,934 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 13:03:05,348 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/common_param_dic.py] [encry ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/common_param_dic.py:132]- 接口参数处理类将文件转为文件流方法异常，异常原因：[Errno 2] No such file or directory: '../hz_file/xzhx.jpg'
2019-09-11 13:06:27,895 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 13:06:28,067 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 13:06:28,068 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 13:06:33,500 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 13:06:33,501 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 13:06:33,509 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 13:08:31,365 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/common_param_dic.py] [encry ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/common_param_dic.py:132]- 接口参数处理类将文件转为文件流方法异常，异常原因：[Errno 2] No such file or directory: '../hz_file/xzhx.jpg'
2019-09-11 13:09:07,153 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 13:09:07,323 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 13:09:07,323 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 13:09:13,844 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 13:09:13,844 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 13:09:13,846 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 13:10:22,550 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 13:10:22,721 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 13:10:22,722 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 13:12:16,445 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/common_param_dic.py] [get_param_name_value ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/common_param_dic.py:114]- 接口参数处理类处理参数名与参数值方法异常，异常原因：'CommonParamDict' object has no attribute 'name_value_list'
2019-09-11 13:12:16,464 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/common_param_dic.py] [get_param_name_value ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/common_param_dic.py:114]- 接口参数处理类处理参数名与参数值方法异常，异常原因：'CommonParamDict' object has no attribute 'name_value_list'
2019-09-11 13:12:18,204 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 13:12:18,296 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/common_param_dic.py] [get_param_name_value ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/common_param_dic.py:114]- 接口参数处理类处理参数名与参数值方法异常，异常原因：'CommonParamDict' object has no attribute 'name_value_list'
2019-09-11 13:12:18,344 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/common_param_dic.py] [get_param_name_value ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/common_param_dic.py:114]- 接口参数处理类处理参数名与参数值方法异常，异常原因：'CommonParamDict' object has no attribute 'name_value_list'
2019-09-11 13:12:18,889 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 13:12:18,889 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 13:12:22,312 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 13:12:22,313 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 13:12:22,314 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 13:12:32,263 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/common_param_dic.py] [get_param_name_value ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/common_param_dic.py:114]- 接口参数处理类处理参数名与参数值方法异常，异常原因：'CommonParamDict' object has no attribute 'name_value_list'
2019-09-11 13:12:32,269 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/common_param_dic.py] [get_param_name_value ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/common_param_dic.py:114]- 接口参数处理类处理参数名与参数值方法异常，异常原因：'CommonParamDict' object has no attribute 'name_value_list'
2019-09-11 13:13:14,339 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/common_param_dic.py] [get_param_name_value ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/common_param_dic.py:114]- 接口参数处理类处理参数名与参数值方法异常，异常原因：'CommonParamDict' object has no attribute 'name_value_list'
2019-09-11 13:13:14,373 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/common_param_dic.py] [get_param_name_value ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/common_param_dic.py:114]- 接口参数处理类处理参数名与参数值方法异常，异常原因：'CommonParamDict' object has no attribute 'name_value_list'
2019-09-11 13:17:58,808 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/common_param_dic.py] [get_param_name_value ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/common_param_dic.py:114]- 接口参数处理类处理参数名与参数值方法异常，异常原因：'CommonParamDict' object has no attribute 'name_value_list'
2019-09-11 13:17:58,825 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/common_param_dic.py] [get_param_name_value ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/common_param_dic.py:114]- 接口参数处理类处理参数名与参数值方法异常，异常原因：'CommonParamDict' object has no attribute 'name_value_list'
2019-09-11 13:18:05,203 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 13:18:05,254 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 13:18:07,554 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 13:18:10,477 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 13:18:10,477 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 13:18:32,421 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 13:18:32,422 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 13:18:32,426 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 13:18:35,250 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/common_param_dic.py] [encry ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/common_param_dic.py:132]- 接口参数处理类将文件转为文件流方法异常，异常原因：[Errno 2] No such file or directory: '../hz_file/xzhx.jpg'
2019-09-11 13:19:49,774 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 13:19:49,952 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 13:19:49,953 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 13:19:51,791 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 13:19:51,792 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 13:19:51,793 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 13:19:53,502 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/common_param_dic.py] [encry ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/common_param_dic.py:132]- 接口参数处理类将文件转为文件流方法异常，异常原因：[Errno 2] No such file or directory: '../hz_file/xzhx.jpg'
2019-09-11 13:21:38,261 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 13:21:38,433 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 13:21:38,433 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 13:21:39,826 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 13:21:39,827 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 13:21:39,832 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 13:21:41,417 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/common_param_dic.py] [encry ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/common_param_dic.py:132]- 接口参数处理类将文件转为文件流方法异常，异常原因：[Errno 2] No such file or directory: '../hz_file/xzhx.jpg'
2019-09-11 13:27:01,183 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 13:27:01,357 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 13:27:01,357 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 13:27:05,364 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 13:27:05,364 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 13:27:05,365 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 13:27:07,682 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/common_param_dic.py] [encry ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/common_param_dic.py:132]- 接口参数处理类将文件转为文件流方法异常，异常原因：[Errno 2] No such file or directory: '/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/project_tree/TSA-IPPS-QZ/jc_imagexzhx.jpg'
2019-09-11 13:28:17,327 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 13:28:17,499 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 13:28:17,499 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 13:28:19,115 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 13:28:19,115 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 13:28:19,117 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 13:28:20,545 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/common_param_dic.py] [encry ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/common_param_dic.py:132]- 接口参数处理类将文件转为文件流方法异常，异常原因：[Errno 2] No such file or directory: '/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/project_tree/TSA-IPPS-QZ/jc_imagexzhx.jpg'
2019-09-11 13:29:36,968 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 13:29:37,145 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 13:29:37,145 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 13:29:38,900 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 13:29:38,901 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 13:29:38,902 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 13:29:40,478 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/common_param_dic.py] [encry ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/common_param_dic.py:132]- 接口参数处理类将文件转为文件流方法异常，异常原因：[Errno 2] No such file or directory: '/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/project_tree/TSA-IPPS-QZ/jc_imagexzhx.jpg'
2019-09-11 13:30:33,757 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 13:30:33,925 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 13:30:33,925 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 13:30:38,906 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 13:30:38,906 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 13:30:38,908 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 13:31:56,003 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 13:31:56,178 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 13:31:56,178 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 13:31:58,242 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 13:31:58,243 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 13:31:58,248 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 13:32:32,910 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 13:32:33,086 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 13:32:33,086 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 13:32:35,356 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 13:32:35,356 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 13:32:35,357 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 13:33:53,204 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 13:33:53,378 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 13:33:53,379 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 13:33:57,236 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 13:33:57,237 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 13:33:57,239 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 13:35:36,318 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 13:35:36,491 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 13:35:36,491 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 13:35:40,530 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 13:35:40,531 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 13:35:40,537 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 13:38:09,915 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 13:38:10,090 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 13:38:10,090 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 13:38:14,163 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 13:38:14,164 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 13:38:14,168 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 13:41:00,750 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 13:41:00,750 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 13:44:06,222 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 13:44:06,224 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 13:46:48,694 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 13:46:48,695 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 13:47:19,502 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/common_param_dic.py] [encry ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/common_param_dic.py:132]- 接口参数处理类将文件转为文件流方法异常，异常原因：[Errno 2] No such file or directory: '/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/project_tree/TSA-IPPS-QZ/jc_image/xzhx.jpg'
2019-09-11 13:50:15,602 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 13:50:15,603 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 13:50:24,923 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/common_param_dic.py] [encry ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/common_param_dic.py:134]- 接口参数处理类将文件转为文件流方法异常，异常原因：[Errno 2] No such file or directory: '/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/project_tree/TSA-IPPS-QZ/jc_image/xzhx.jpg'
2019-09-11 13:52:03,644 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 13:52:03,645 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 13:52:10,175 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/common_param_dic.py] [encry ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/common_param_dic.py:134]- 接口参数处理类将文件转为文件流方法异常，异常原因：[Errno 2] No such file or directory: '/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/project_tree/TSA-IPPS-QZ/jc_image/xzhx.jpg'
2019-09-11 13:53:43,138 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 13:53:43,140 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 13:54:04,293 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/common_param_dic.py] [encry ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/common_param_dic.py:134]- 接口参数处理类将文件转为文件流方法异常，异常原因：[Errno 2] No such file or directory: '/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/project_tree/TSA-IPPS-QZ/jc_image/xzhx.jpg'
2019-09-11 13:55:33,235 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 13:55:33,237 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 13:57:41,219 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 13:57:41,220 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 14:02:29,530 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 14:02:49,193 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 14:02:49,275 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 14:02:49,275 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 14:02:49,276 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 14:02:49,276 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 14:02:49,276 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 14:04:42,680 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 14:04:42,764 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 14:04:42,764 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 14:04:42,765 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 14:04:42,765 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 14:04:42,765 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 14:08:04,476 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 14:08:04,557 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 14:08:04,557 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 14:08:04,558 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 14:08:04,558 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 14:08:04,558 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 14:28:02,934 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 14:28:03,016 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 14:28:03,016 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 14:28:03,017 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 14:28:03,017 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 14:28:03,017 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 14:30:54,316 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 14:30:54,401 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 14:30:54,401 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 14:30:54,402 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 14:30:54,402 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 14:30:54,402 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 14:53:07,144 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 14:53:07,226 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 14:53:07,226 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 14:53:07,227 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 14:53:07,227 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 14:53:07,227 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 15:02:17,037 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 15:02:17,118 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 15:02:17,118 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 15:02:17,119 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 15:02:17,119 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 15:02:17,120 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 15:13:48,153 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 15:13:48,236 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 15:13:48,237 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 15:13:48,237 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 15:13:48,237 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 15:13:48,238 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 15:18:02,696 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 15:18:02,781 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 15:18:02,781 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 15:18:02,782 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 15:18:02,782 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 15:18:02,782 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 15:24:41,571 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 15:24:41,655 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 15:24:41,655 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 15:24:41,656 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 15:24:41,656 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 15:24:41,657 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 15:26:07,820 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 15:26:07,902 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 15:26:07,903 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 15:26:07,903 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 15:26:07,903 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 15:26:07,904 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 15:27:25,429 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 15:27:25,507 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 15:27:25,507 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 15:27:25,508 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 15:27:25,508 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 15:27:25,508 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 15:27:53,768 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 15:27:53,850 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 15:27:53,850 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 15:27:53,851 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 15:27:53,851 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 15:27:53,852 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 15:32:11,478 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 15:32:11,557 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 15:32:11,557 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 15:32:11,558 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 15:32:11,558 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 15:32:11,558 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 15:32:38,426 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 15:32:38,511 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 15:32:38,511 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 15:32:38,512 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 15:32:38,512 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 15:32:38,512 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 15:32:56,061 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 15:32:56,139 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 15:32:56,139 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 15:32:56,140 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 15:32:56,140 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 15:32:56,140 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 15:35:00,803 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 15:35:00,882 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 15:35:00,882 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 15:35:00,883 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 15:35:00,883 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 15:35:00,883 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 16:20:21,633 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 16:20:21,713 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 16:20:21,713 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 16:20:21,714 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 16:20:21,714 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 16:20:21,714 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-11 16:22:59,479 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 16:22:59,481 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 16:31:24,167 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 16:31:24,169 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 16:35:22,339 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 16:35:22,340 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 16:49:38,203 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 16:49:38,204 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 16:52:14,485 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 16:52:14,485 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 16:52:47,910 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 16:52:47,911 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 16:54:14,695 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 16:54:14,697 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 16:54:30,655 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 16:54:30,655 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 16:55:05,911 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 16:55:05,913 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 16:56:57,108 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 16:56:57,109 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 16:59:18,907 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 16:59:18,907 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 17:23:51,639 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 17:23:51,640 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 17:24:18,599 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 17:24:18,601 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 17:25:59,584 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 17:25:59,589 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 17:27:03,001 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 17:27:03,001 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 17:28:13,710 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 17:28:13,711 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 17:34:21,053 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 17:34:21,053 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 17:34:31,370 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 17:34:31,371 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 17:34:44,777 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 17:34:44,778 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 17:35:05,556 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 17:35:05,557 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 17:36:16,795 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 17:36:16,795 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 17:36:31,214 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 17:36:31,216 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 17:36:43,827 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 17:36:43,828 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 17:37:10,346 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 17:37:10,346 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 17:38:15,276 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 17:38:15,278 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 17:46:07,399 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 17:46:07,399 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 17:46:53,559 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 17:46:53,559 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 17:57:55,680 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 17:57:55,681 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 17:58:03,910 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 17:58:03,911 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 17:58:12,128 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 17:58:12,130 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 17:59:21,474 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 17:59:21,475 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 17:59:35,720 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 17:59:35,720 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 18:00:59,445 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 18:00:59,446 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 18:01:33,701 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 18:01:33,702 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 18:01:40,147 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 18:01:40,148 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 18:01:47,209 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 18:01:47,211 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 18:02:27,196 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-11 18:02:27,197 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
